### ISSUE TITLE
Package "Spatie/laravel-ray" is not installed on staging site

### ISSUE THREAD

**Issue by Ihabafia** [spatie/laravel-ray#100]
**Describe the bug**
laravel-ray is working great in local, but when I deploy my app to forge I start getting that error laravel-ray is not installed.1

**Versions**
1.3.1

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.9.1
- spatie/laravel-ray package version (if applicable): 1.6.0

PHP version:
Laravel version: 7.4.8

**To Reproduce**
1. Application protected

**Expected behavior**
It shouldn't ask for the package while I installed the package as "require-dev".
<img width="1223" alt="error" src="https://user-images.githubusercontent.com/6062692/104705908-775e4400-56e8-11eb-83cd-0dd3c0aa4375.png">

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX
 - Version 11.1
 
 **Additional context**
Every time I install the package locally to use it, once I push to forge, I start getting the error.

Thank you,

**Comment by dillingham** [comment]
`require-dev` can be in staging.  try adding `--no-dev`

**Comment by Ihabafia** [comment]
I tried that, but still didn't work :(

**Comment by pixels-for-breakfast** [comment]
Having the same issue. Just tried it under Windows 10. Bought and downloaded it on my Mac afterwards and was trying to get it running, but unfortunately to no avail. I've installed it both as a regular dependency and a dev-dependency; didn't work in both cases. Any help would be appreciated.

**Comment by pixels-for-breakfast** [comment]
Nevermind, got it working by upgrading composer to v2 (`composer selfupdate --2`) and require laravel-ray again. Works amazing!
