### ISSUE TITLE
Not working on dockerized app

### ISSUE THREAD

**Issue by gguney** [spatie/laravel-ray#106]
**Describe the bug**
I have dockerized app on mac os. I did not buy it I'm just trying to if it fits my needs. When I try to use the app with tinker 

`>>> ray("test");
=> Spatie\LaravelRay\Ray {#3506
     +settings: Spatie\Ray\Settings\Settings {#173},
     +uuid: "2986da46-a516-4b14-832a-745cdf10a272",
   }
>>> 
`
The ray apps captures nothing. I also created ray.php for docker config.

**Versions**
spatie/laravel-ray                 1.7.1   Easily debug Laravel apps
spatie/ray                         1.11.0  Debug with Ray to fix problems faster

PHP version:
PHP 8
Laravel version:
Laravel 8.22.1
.

**Comment by freekmurze** [comment]
Did you try any of the Docker hints in our docs?

**Comment by gguney** [comment]
I have docker v19.03.1,  so I can not add 

`    extra_hosts: # <-- this is required
      - "host.docker.internal:host-gateway" # <-- this is required`

**Comment by freekmurze** [comment]
Can you upgrade to the latest version of Docker?

**Comment by gguney** [comment]
I'm using docker-compose for it but it throws an error: 

 invalid IP address in add-host: "host-gateway"

**Comment by freekmurze** [comment]
I hope other docker users here can give you a hint on how to get it working

**Comment by gguney** [comment]
I did everything on your document but there is a problem with the document I guess. I was thinking to buy it but there should be proper support for it if you are selling something. 

"Other docker users" is not proper support.

**Comment by freekmurze** [comment]
Ok, closing this for now. I'm pretty sure the problem lies with configuration at your end. 

Should you find a solution, let me know and I'll document it to help others.

**Comment by gguney** [comment]
I dont think you should sell this product because of lack of support. Since you closed the issue I dont think anyone will look at it.

Anyway hope you find a way to solve this support issue. Till then, I cant see any way to use this product for development and i wont recommend to anyone.

**Comment by hasnatbabur** [comment]
I just upgraded docker engine and everything working fine with:
RAY_HOST=host.docker.internal
RAY_PORT=23517
Thanks

**Comment by ractoon** [comment]
In your docker compose file are you defining ports for your container? I needed to add the `RAY_PORT` (default 23517) to the definitions, e.g.

```
...
ports:
      - 23517
...
```
