### ISSUE TITLE
Maximum execution time of 120 seconds exceeded when using pause on ray

### ISSUE THREAD

**Issue by lovekrissh143** [spatie/laravel-ray#111]
The expected behavior should be until I continue or stop the execution, isn't it @freekmurze ?

I could achieve a greater execution time by doing a little bit of key taps on php info. but Should I?

![image](https://user-images.githubusercontent.com/48975027/105032693-1d110a80-5a7d-11eb-9fd1-ddfda246e743.png)

![image](https://user-images.githubusercontent.com/48975027/105032723-2ac69000-5a7d-11eb-962a-33c5d4698198.png)

And also when I click on stop the execution, it throws an exception. 

Should ray be throwing an exception or rather logging a message regarding execution being stopped. 

I just don't know what could be the best experience.

You're the best to wisely choose that. :)

**Comment by freekmurze** [comment]
Under all operating systems, sleep will not count against the time limit.

I've just learned that the only exception is Windows, and I'm assuming you're using that.

I'll add a note in our docs for windows users.

**Comment by lovekrissh143** [comment]
yeah you're right @freekmurze. 

Windows is what gets me going for productivity and chills me out with it's awesome AAA game support and gigantic application library which others lack. :)
