### ISSUE TITLE
[Solved] Ray stuck on old version / Satis not providing most recent Ray version

### ISSUE THREAD

**Issue by SebastianSchoeps** [spatie/laravel-ray#112]
As a reference for others; can be closed right away.

I was wondering why a composer update still gave me v1.3 (current version: 1.8). So I put 1.8 in my composer.json (`"spatie/laravel-ray": "^1.8"`). When running `composer update` I got the following error message:

```Root composer.json requires spatie/laravel-ray ^1.8, it is satisfiable by spatie/laravel-ray[1.8.0] from composer repo (https://repo.packagist.org) but spatie/laravel-ray[dev-master, 1.0.0, ..., 1.3.0] from composer repo (https://satis.spatie.be) has higher repository priority.```

I have `satis.spatie.be` configured because I also use Medialibrary Pro in the same project. This repository is also in Spatie's Satis and has a higher priority than Packagist, but at this time v1.3 was the most recent version on Satis. That's why I was stuck at 1.3.

### Solution
Repository priority is documented [here](https://getcomposer.org/doc/articles/repository-priorities.md); I used the following approach:
```
"repositories": [
    {
        "type": "composer",
        "url": "https://satis.spatie.be",
        "only": ["spatie/laravel-medialibrary-pro"]
    }
],
```

Spatie, maybe you want to comment on this, or just close it.

**Comment by freekmurze** [comment]
Thanks for bringing this to our attention.

Meanwhile, I have remove Ray from our Satis.
