### ISSUE TITLE
Getting `<code>null</code>` instead of `null`

### ISSUE THREAD

**Issue by mokhosh** [spatie/laravel-ray#115]
**Describe the bug**
I'm passing a model attribute to ray. When it's null, I get `<code>null</code>` instead of just `null`.

**Versions**
1.9 (Latest)

You can use `composer show` to get the version numbers of:
- spatie/laravel-ray                 1.8.0 
- spatie/ray                         1.14.0

PHP version:
Laravel version: 8.0

**Comment by freekmurze** [comment]
Could you give me a little code example to try?

**Comment by mokhosh** [comment]
I tried to create a simple example like this:
```php
Route::get('/',function(){ ray(auth()->user()->nonExistingProperty);});
```
but weirdly enough it gives me `null` as expected.

So, I started trying all kinds of combinations until I landed on this:
- You must be passing an attribute that exists on the model
- The attribute must be nullable in db layer
- The attribute must have a default value defined through `$attributes` property on model class
- The attribute must have a null value on the model you're using

I know this is a very very edge case, and it might not even be worth your time to debug. It also doesn't create a problem for me. I just thought I would let you know.

**Comment by lovekrissh143** [comment]
What a luck!

That edge case I was wondering about after reading it, and mamma mia! I got it just after couple minutes of debugging on my own website. I wasn't trying to replicate or something, it just happened.

Now I've put a snap of the code that triggered it.

![snap1054AM28JAN2021](https://user-images.githubusercontent.com/48975027/106094400-f24b4400-6157-11eb-88dd-af8568d0203d.png)

how it looks when printed on Ray

![Screenshot 2021-01-28 105605](https://user-images.githubusercontent.com/48975027/106094444-0abb5e80-6158-11eb-92c7-a62cdbea61f6.png)

PHP v7.4
Composer v2.0
Laravel : v8.25.0
- spatie/laravel-ray v1.9.1
- spatie/ray v1.17.1

@freekmurze you definitely know what's going on.

:)

**Comment by desaintflorent** [comment]
`Ray(implode(' ', []));` display `<code>null</code>` instead of `""` like  in Tinkerwell

**Comment by freekmurze** [comment]
Thanks for reporting! 

I've fixed this in the upcoming Ray v1.11.1 which will be released later this week.

**Comment by lovekrissh143** [comment]
That's great man!

**Comment by mokhosh** [comment]
@freekmurze legend
