### ISSUE TITLE
Some methods missing in lumen

### ISSUE THREAD

**Issue by f1mp3r** [spatie/laravel-ray#119]
**Describe the bug**
I am using ray in lumen and it works okay, except when I try to log queries.
When running ray()->showQueries(); it throws
Method showQueries does not exist

**Versions**
- spatie/ray package version: 1.17.0
- spatie/laravel-ray package version: 1.9.1 

PHP version: 7.4.12
Lumen version: 8.2.1

**Expected behavior**
Should work as documented

**Desktop:**
 - OS: masOS Big Sur
 - Version 11.2 Beta

**Comment by freekmurze** [comment]
Could you create and share an minimal example app to demonstrate the bug?

**Comment by f1mp3r** [comment]
I made a showcase app: https://github.com/f1mp3r/lumen-ray
1. Clone
2. composer install
3. Create dummy database and set up .env database config
4. php artisan migrate:fresh --seed
5. php artisan raytest

**Comment by freekmurze** [comment]
You need to manually register the service provider, as Lumen doesn't seem to do that automatically.
Add this to `bootstrap/app.php`

``` 
$app->register(\Spatie\LaravelRay\RayServiceProvider::class);
```
