### ISSUE TITLE
[bug] laravel-ray Vers. 1.9.3 is not sending Log Calls to ray

### ISSUE THREAD

**Issue by ibrainventures** [spatie/laravel-ray#125]
**Describe the bug**

Error Logs - (my case a Mysql Error) are not transmitted to Ray. 

Version 1.9.2 and lower are working fine. (downgraded to 1.9.2 and tested)

**Versions**
Ray version (you can see this in "About Ray"):

(Ray / Windows 1.12.0.0)

You can use `composer show` to get the version numbers of:
- spatie/ray package version:        1.17.1
- spatie/laravel-ray package version (if applicable):  laravel-ray    1.9.3

PHP version: v7.4.14
Laravel version: v8.25.0

**Comment by freekmurze** [comment]
Hi,

this have been fixed in the latest version of `laravel-ray`.

If this does not work for you, please create a minimal app for us to easily recreate the issue.
