### ISSUE TITLE
Ray Config local_path issue on Linux

### ISSUE THREAD

**Issue by CodyPChristian** [spatie/laravel-ray#128]
**Describe the bug**
I'm trying to use Ray on Linux Mint and setting the local_path gives weird results. Here is a few examples:

| local_path  | ray result |
| ------------- | ------------- |
| `/home/cody/dev/`  |  `~/dev/views/app/...`  |
| `/home/cody/dev/tba-reviews/`  |  `~/dev/tba-reviews/views/app/...`  |

Actual project is located at `/home/cody/dev/tba-reviews/`
config is at `/home/cody/dev/tba-reviews/ray.php`

**Versions**
Ray version (you can see this in "About Ray"): 1.12.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.17.2
- spatie/laravel-ray package version (if applicable): 1.11.2

PHP version: 7.4.7
Laravel version: 8.25.0

**Comment by patinthehat** [comment]
In Linux, `~` is shorthand for your home directory path.  
For example: `~/dev/myproject/views` is shorthand for `/home/username/dev/myproject/views`.

Does this explain what you're seeing in Ray?

**Comment by CodyPChristian** [comment]
@patinthehat Thanks, yes I was aware of that :P and the ~ vs /home/cody/ part isnt the issue here. The actual issue is it resolving to the project root. If you notice the first part is fine in both examples. For example if I set the local_path to be `/home/cody/dev/tba-reviews/` and I click in ray on a filename I get an error with this: ```Path Doesnt Exist, the path `~/dev/tba-reviews/views/app/Http/Livewire/CompanySwitcher.php` does not seem to exist anymore on disk.``` which makes sense because its not at that path. Its actually at `/home/cody/dev/tba-reviews/app/Http/Livewire/CompanySwitcher.php` so where is it pulling 'views' from? Its doing that to all files.

**Comment by patinthehat** [comment]
> Thanks, yes I was aware of that :P

My apologies, I misunderstood you. :rofl: 

I see what you're saying - can you share the portion of the code that you're calling ray from?

**Comment by CodyPChristian** [comment]
@pascalbaljet no problem :) so Im currently calling ` ray()->showQueries();` from inside of my mount() function in `/home/cody/dev/tba-reviews/app/Http/Livewire/Users.php` but the other liveware component you saw in my previous example is also loaded because its on the same page.

**Comment by patinthehat** [comment]
@CodyPChristian Nothing jumps out at me from a few quick tests...

Can you provide a sample repo that reproduces the issue?

**Comment by CodyPChristian** [comment]
@patinthehat ok sounds good, Ill try it later today on a fresh L8 install and if it does it then I will push it up to a public repo and send it over to you. I wonder if the dash/hyphen is causing it?

**Comment by patinthehat** [comment]
@CodyPChristian I tracked it down - it's an issue with the way the local/remote paths are rewritten in `spatie/ray`.  I've got a fix, so hang tight.  I'll update this thread when I submit the PR.

**Comment by patinthehat** [comment]
@CodyPChristian I submitted a PR (spatie/ray#269) that should (hopefully) resolve your issue.

**Comment by freekmurze** [comment]
Thanks again for that PR @patinthehat 

@CodyPChristian Let us now if the latest version works for you.

**Comment by CodyPChristian** [comment]
@patinthehat @freekmurze yes that worked great! Thank you! :)
