### ISSUE TITLE
Custom DB connection not resolving

### ISSUE THREAD

**Issue by leigeber** [spatie/laravel-ray#135]
We're overriding the pgsql connection with an extended custom connection. This has been working great until a recent Ray update. The closure is never called so naturally all kinds of stuff application-wide starts to fall apart with undefined methods and whatnot. Seems like its likely a dependency in Ray since locking in on older versions doesn't eliminate the issue.

```
Connection::resolverFor('pgsql', static function($connection, $database, $prefix, $config) {
	return new CustomConnection($connection, $database, $prefix, $config);
});
```

Happy to provide more info or check anything on our end.

PHP version: 8.0.0
Laravel version: 8.26.1

Add `Connection::resolverFor` override in your service provider. The closure doesn't execute.

**Comment by freekmurze** [comment]
Could you provide us with the full stack trace and a minimal app that allows us to easily reproduce the issue?
