### ISSUE TITLE
Register watchers on boot stage

### ISSUE THREAD

**Issue by zlodes** [spatie/laravel-ray#137]
Hi!

I think that we need to register Watchers on `boot` stage.
https://github.com/spatie/laravel-ray/blob/master/src/RayServiceProvider.php#L38

Some dependencies may not be resolved or some of them may be changed (rebinding). 
I'm faced this problem with the custom event dispatcher.

About events: we need to register listeners on `boot` stage: [Laravel docs reference](https://laravel.com/docs/8.x/events#manually-registering-events)

Another solution is using resolving events like this:
```php
public function register()
{
	  $this->app->afterResolving('events', function (DispatcherContract $events): void {
	          $events->listen('*', function (string $eventName, array $arguments) {
	              if (! $this->enabled()) {
	                  return;
	              }
	      
	              $payload = new EventPayload($eventName, $arguments);
	      
	              $this->app->make(Ray::class)->sendRequest($payload);
	          });
	      });
	  }
```

**Comment by zlodes** [comment]
I think the https://github.com/spatie/laravel-ray/issues/135 issue will be resolved by fixing this.

**Comment by leigeber** [comment]
Confirmed moving the watchers to boot does resolve #135. Thanks @zlodes.

**Comment by patinthehat** [comment]
@zlodes I will submit a PR that moves the watchers registration to `boot` as confirmed by @leigeber.  
I'll update this issue once the PR is submitted.

**Comment by patinthehat** [comment]
@zlodes I submitted PR #138, which registers the watchers from the Provider's `boot()` method as requested. Please let me know if this resolves your issue (assuming the PR is accepted).

**Comment by freekmurze** [comment]
I'm going to assume that #138 which has been tagged as v1.2.1 will solve this problem. If not, open up a new issue.

**Comment by zlodes** [comment]
@patinthehat @freekmurze Thanks! Works after update to 1.12.1.
