### ISSUE TITLE
send_queries_to_ray is still performing DB action when disabled

### ISSUE THREAD

**Issue by esseremmerik** [spatie/laravel-ray#139]
**Describe the bug**
Perhaps it shoudn't be marked as bug, but the way it is implemented at te moment, you cannot really change the loading behavior of Ray.

The QueryWatcher is able to be activated by a setting, see:
https://github.com/spatie/laravel-ray/blob/master/src/Watchers/QueryWatcher.php#L20

Our booting process is a bit specific by setting database connections, so at that time the connection is not available yet. We can solve this at our side by changing the boot process, but in my opinion, the setting check could be performed before the DB::listen call, as there is no need for this call if the setting is disabled.

**Versions**
Ray version (you can see this in "About Ray"):
You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.19
- spatie/laravel-ray package version: 1.12.1 

PHP version: 7.4
Laravel version: 7.30.4

**To Reproduce**
Bit difficult to reproduce if you don't have the specific database boot process as we have.
x
**Expected behavior**
Skip function logic when setting is disabled, move the setting check to line 18

**Comment by esseremmerik** [comment]
Perhaps solution implemented in this issue (https://github.com/spatie/laravel-ray/issues/135) will also solve this issue in another way, but still, is the DB call needed when the setting is disabled :)

**Comment by freekmurze** [comment]
Could you submit a non-breaking PR that would fix this issue for you?

**Comment by esseremmerik** [comment]
Hereby: https://github.com/spatie/laravel-ray/pull/140/files

**Comment by freekmurze** [comment]
We'll continue the conversation in #140
