### ISSUE TITLE
When laral-ray required in composer, but laravel is not used, ray does not behave as expected

### ISSUE THREAD

**Issue by Polfo** [spatie/laravel-ray#161]
When laravel-ray is composer required, but ray() is run outside the laravel framework, strange things happen because ray() references the laravel version of ray, not the spatie/ray version of ray. 

An example is that ray()->disable() does nothing. It does not disable ray, it also does not produce an error.

That explains why ray()->disable() did not change anything here:
_Originally posted by @Polfo in https://github.com/spatie/laravel-ray/issues/148#issuecomment-775058169_

Versions:
spatie/laravel-ray (1.12.6)
spatie/ray (1.19.4)
php 7.4.9

**Comment by freekmurze** [comment]
We recommend to only install laravel-ray in a Laravel app
