### ISSUE TITLE
Ray has died with a red screen on my Linux Mint - Something went wrong here: Reload Ray to try again.

### ISSUE THREAD

**Issue by eugenevdm** [spatie/laravel-ray#165]
**Describe the bug**

Ray was working fine for a few weeks. Then I noticed that an error was repeating, something like:

`Missing }` and then I had to click on ErrorHandler which didn't show the real problem.

I don't recall the precise message but I can tell you it was repeating and I can't use Ray anymore at all.

**Versions**

Bit of a mystery here, as I click on Ray-1.13.0.AppImage but Menu/About says 1.12.0

- spatie/ray package version: 1.20.0
- spatie/laravel-ray package version (if applicable): 1.13.0

PHP version: 7.4.15

Laravel version: 8.29.0

**To Reproduce**

1. Start Ray
2. A red screen appears, "Something went wrong here. Reload Ray to try again."
3. Click Reload Ray. Nothing happens.
4. Click View menu, New Blank Screen and Clear History. Nothing happens.

**Expected behavior**

Ray should work and clearing screens should "reset" it.

**Screenshots**

![image](https://user-images.githubusercontent.com/1836436/108972740-4892a080-768c-11eb-9918-e0a917986eb5.png)

**Desktop (please complete the following information):**

 - OS: Linux Mint
 - Version 20 Ulyana
 
 **Additional context**

If Ray has some kind of buffer that stores messaging, my belief is it was overwhelmed by the constant repeats of "Missing }" and eventually just crashed due to too much data. One would expect "New Blank Screen..." fixes the problem, but perhaps because it's so overwhelmed it's now just fubar. 

I love Ray so please let Ray love me back <3

**Comment by freekmurze** [comment]
Could you create a minimal app to recreate the issue your are experiencing? This would help us a lot debugging and fixing this issue.

**Comment by eugenevdm** [comment]
Ok I did that, started a new project and it's working. I'm going to close this issue for now until I can figure out what's wrong with my project. Perhaps vendor files are broken I'm not sure but will come back if there is still an issue.
