### ISSUE TITLE
Document how to open ray window

### ISSUE THREAD

**Issue by Polfo** [spatie/laravel-ray#17]
How can we display the ray output?
Should it be opened in a separate window like Telescope ? I tried http://localhost:23517/ but that does not work.
Should it be visible together with the loaded page? I looked at the page source, but nothing is added.

**Comment by freekmurze** [comment]
Out put is sent to a dedicated app. You can download it here: https://myray.app

**Comment by Polfo** [comment]
OK, please enhance the documentation by saying the app should  be downloaded and installed also

> Getting started
> To get started you should buy a license for the Ray app in our store, and install the free package into your app.

**Comment by freekmurze** [comment]
I'll improve this soon!
