### ISSUE TITLE
typos: the laravel configuration file has spaces in the env values instead of underscores

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-ray#174]
The file located here https://spatie.be/docs/ray/v1/configuration/laravel

Has these 5 `env` values with a space in it. Those values would be invalid if set in an `.env` file

```
env('SEND CACHE_TO_RAY', false)
env('SEND JOBS_TO_RAY', false)
env('SEND QUERIES_TO_RAY', false)
env('SEND REQUESTS_TO_RAY', false)
env('SEND VIEWS_TO_RAY', false)
```

**Comment by freekmurze** [comment]
Could you send a PR to fox this?

**Comment by vesper8** [comment]
@freekmurze Didn't realize I could.. done! https://github.com/spatie/ray/pull/366
