### ISSUE TITLE
Getting a "Database connection [mysql] not configured" error

### ISSUE THREAD

**Issue by dougfelton** [spatie/laravel-ray#177]
When attempting to install the laravel-ray package, I get this error: "Database connection [mysql] not configured".  This is presumably because I don't actually have a connection named "mysql" in config/database.php.

There is a simple workaround for me:  if I simply copy and paste of one of my other connections arrays in database.php, and rename the copy to "mysql", the laravel-ray package installs and works just fine.  But having to have the extra array in databases.php that does nothing except allow me to use Ray seems like a bug?  If not a bug, then an inconvenience?

**Versions**

Ray version: 1.14.7.0
spatie/ray package version: 1.17.1
spatie/laravel-ray package version: 1.21.2
PHP version: 7.4.8
Laravel version: 8.35.1

**To Reproduce**
1. Rename the 'mysql' array in config/database.php to 'mysql-test'
2. Rename any references to the 'mysql' connection in the app to 'mysql-test'
3. Attempt to install laravel-ray

**Expected behavior**

I would expect laravel-ray to install and work without the existence of a config/database.php connection named 'mysql'

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Version 20H2
 
 **Additional context**

This is not a showstopping bug at all! It's just unexpected and a minor inconvenience.  But I thought it was worth reporting.

**Comment by freekmurze** [comment]
Could you post the error that you saw (maybe use "Share" on the exception page, and paste the link here)

**Comment by dougfelton** [comment]
Sure.  Here you go: https://flareapp.io/share/W7zljavm#F20

**Comment by RomkaLTU** [comment]
Similar issue here, in our project we even dont use any Database, but getting "Database (homestead) does not exist. (SQL: PRAGMA foreign_keys = ON;)" after Ray install.

**Comment by tux3d0** [comment]
What I did was go to config/database.php
copied my mysql DB connection info, pasted it below it and renmaed that section. 

I could have just renamed the mysql driver section to system, but im only playing with it right now and being lazy,.

**Comment by Polfo** [comment]
In my case `php artisan config:clear` solved the issue

**Comment by sudesh-rd** [comment]
In my case, I could not even run `php artisan config:clear`, without getting error.

Deleting `bootstrap\cache\config.php` file solved the issue
