### ISSUE TITLE
Windows and PHPstorm compatability?

### ISSUE THREAD

**Issue by colinmackinlay** [spatie/laravel-ray#18]
Sorry to be dense and have to raise an issue... 

Instant purchase for me, looks great but after installing with `composer require...` and saving ray.php to project root what actually gets ray running? Nothing obvious to get a process started. Have put a simple `ray('Hello')` but nothing happens.

Windows 10, PHPstorm, Laragon

**Comment by freekmurze** [comment]
The installation instructions are here: https://spatie.be/docs/ray/v1/getting-started/installation-in-laravel

**Comment by koost89** [comment]
@colinmackinlay I had the same issue (running on WSL2 though)
With the 1.0.3 version that was just tagged I got my output

I had to make sure to pass my local IPv4 in the ray config file.  (through ifconfig in cmd/powershell)

**Comment by colinmackinlay** [comment]
Thanks for getting back to me @freekmurze but I have followed those:
`composer require spatie/laravel-ray` and have a `ray.php` file but nothing happens which is why I requested help

The docs also reference launching/hiding from an IDE but I can't see anything that will get PHPstorm to recognise that here:
https://spatie.be/docs/ray/v1/getting-started/discovering-the-ray-app#hiding-the-app-using-the-hotkey

**Comment by freekmurze** [comment]
I don't have experience with Laragon, so I can't help you with that. Ray registers global hotkeys independent of PHPStorm. The hotkeys are displayed in the Ray app itself (you can change them in the preferences)

<img width="740" alt="image" src="https://user-images.githubusercontent.com/483853/103941612-697c5200-512f-11eb-8d0f-d0faaa9c28b3.png">


If you have problems installing the package, please try it in a fresh Laravel app (of framework of your choice)

**Comment by colinmackinlay** [comment]
Thanks @freekmurze . I missed the absolutely obvious by jumping straight from Twitter to purchase and then into the docs to install. Can you see what's missing in that....?

... downloading and installing the Ray app itself!!! Might be worth a mention in the docs for idiots like me....

The other thing you probably know already is that Chrome tries to block the download as unsafe and Windows tries to stop it being installed. I guess you'd need to sign the installer with something they'd recognise

Works like a dream after that!

**Comment by freekmurze** [comment]
lol 🙂 It's actually in the docs: https://spatie.be/docs/ray/v1/getting-started/download-the-free-demo

I'll improve those frictions on Windows soon. Enjoy Ray!
