### ISSUE TITLE
Changing configuration using ray.php not working

### ISSUE THREAD

**Issue by 4nik3t** [spatie/laravel-ray#184]
I have created a ray.php in my project root and made some changes as below to the file

```php
    'send_dumps_to_ray' => false,
    'send_log_calls_to_ray' => env('SEND_LOG_CALLS_TO_RAY', true),
```
But still, when I do a dd it's getting logged into Ray and also all exceptions are getting logged into ray how can I disable this. As it is not working for me

**Versions**
Ray version (you can see this in "About Ray"): 1.14.7.0

- spatie/ray package version: 1.21.2
- spatie/laravel-ray package version (if applicable): 1.17.2

PHP version: 8.0.3
Laravel version: v8.36.1

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by 4nik3t** [comment]
Can somebody guide me through this. Or should I put in some more description to the problem? Eagerly waiting for a reply :-)

**Comment by freekmurze** [comment]
What happens I you set `send_log_calls_to_ray` in the config file to `false`?

**Comment by 4nik3t** [comment]
Ok, I will put all my observations here about the problems I am facing. Firstly this issue mentioned [here](spatie/ray#382). I have set send_dumps_to_ray to false as show below but still whenever I do a dd it is sending it to ray

```php
'send_dumps_to_ray' => false,
```

Here is the code block
![image](https://user-images.githubusercontent.com/48653948/116185403-288c6580-a73f-11eb-8a90-40fa8d6b9a7b.png)

Output in ray
![image](https://user-images.githubusercontent.com/48653948/116185315-f8dd5d80-a73e-11eb-8f6b-1fc5321eee3e.png)


> What happens I you set `send_log_calls_to_ray` in the config file to `false`?

When I do this 

```php
'send_log_calls_to_ray' => env('SEND_LOG_CALLS_TO_RAY', false),
```
It does not log to ray

But when I set this to true its logs into ray so this is working as expected.
```php
Log::info('Inside log function');
```
![image](https://user-images.githubusercontent.com/48653948/116186069-8bcac780-a740-11eb-8356-c4749fdf1f59.png)

**Comment by 4nik3t** [comment]
@freekmurze Please let me know if you need anything else to be done at my end

**Comment by Nielsvanpach** [comment]
> I want to know If I can disable exception logging altogether in ray?

Does this work for you?
```
'send_exceptions_to_ray' => false,
```

I can reproduce the dump issue: https://github.com/spatie/laravel-ray/pull/189
We'll look into it.

**Comment by 4nik3t** [comment]
> Does this work for you?
> 
> ```
> 'send_exceptions_to_ray' => false,
> ```

Yeah, this works for me. Not sure if it's intentional but this is not documented [here](https://spatie.be/docs/ray/v1/configuration/laravel)

Anyways I will wait for the dump fix.

**Comment by Nielsvanpach** [comment]
Dumps can be disabled in the latest release (1.17.3)

I think this solves the last part of your problem, so I'm closing this one.
