### ISSUE TITLE
Error in production when using emailOutputOnFailure

### ISSUE THREAD

**Issue by Algeneralo** [spatie/laravel-ray#186]
**Describe the bug**
I tried to use emailOutputOnFailure on command, then this issue appear on flare, I tried even to set `RAY_ENABLED` to false, but nothing happened also

You can use `composer show` to get the version numbers of:
- spatie/laravel-ray package version (if applicable): 1.12

PHP version:7.4
Laravel version:8.31

**To Reproduce**
1. Install laravel-ray
2. create new command and register it in the Kernel
3. set emailOutputOnFailure function for that command

Flare link for the bug [https://flareapp.io/share/Lm8pNzpm#F47](url)

**Comment by freekmurze** [comment]
Does is work for you, if you change [this line](https://flareapp.io/share/Lm8pNzpm#F47L48) to 

```php
string $html = null
```
