### ISSUE TITLE
Method showJobs does not exists

### ISSUE THREAD

**Issue by dela-dels** [spatie/laravel-ray#188]
Hi Guys,
So in the process of trying to test jobs using ray, I came accorss the ```jobs()``` or ```showJobs()``` methods in the docs.
Unfortunately, when I try to use either of them, I get a ```Method showJobs does not exist.``` or ```Method jobs does not exist.```

Is there something I am not doing right?
I am using the current version of the ray app and updated the laravel-ray packge via composer.

And this is the piece of code I am trying to run: 
```php
ray()->showJobs(function () use ($request) {
      ReduceProductStockQuantity::dispatch($request->validated()['invoice_id']);
});
```
Thank you for an awesome product by the way.  🙏🏽

**Comment by freekmurze** [comment]
Make sure you install `spatie/laravel-ray` and not `spatie/ray`.
