### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by timrspratt** [spatie/laravel-ray#19]
Hi guys, great package. My question is, would you consider merging a PR that adds Laravel 6 support?

I know you like to keep things current, hence, why I'm checking before I spend the time on updating the composer versions, git hub action yml etc.

The reason for Laravel 6 support is the projects my company work on require the LTS version (client requirements to have the longer support window).

I don't feel there is anything in the illuminate packages that is "breaking", but you will know more than me I'm sure.

Thanks

**Comment by freekmurze** [comment]
> Hi guys, great package. My question is, would you consider merging a PR that adds Laravel 6 support?

If all tests pass, I'll consider merging it in. 

You should also make sure that tests functions work correctly on Laravel 6
https://github.com/spatie/laravel-ray/blob/c03f16f25f870c4c49caf556e138db1fcca0b674/src/OriginFactory.php#L60-L82

**Comment by vmitchell85** [comment]
@timrspratt In case any of this helps:

I attempted a quick version of this package adding 6.0 support for the illuminate packages and ran into a ramsey UUID compatibility issue in the main [Ray package](https://github.com/spatie/ray)

**Comment by SebastiaanKloos** [comment]
> @timrspratt In case any of this helps:
> 
> 
> 
> I attempted a quick version of this package adding 6.0 support for the illuminate packages and ran into a ramsey UUID compatibility issue in the main [Ray package](https://github.com/spatie/ray)

I made it work on Laravel 6. Take a look at my fork for reference:

https://github.com/kloos-dev/ray/tree/ocms

**Comment by timrspratt** [comment]
@vmitchell85 ah ok, so the main ray ramsey/uuid dependency needs sorting first before we even consider this. Any idea what the fail was, was it phpunit version?

**Comment by vmitchell85** [comment]
@timrspratt I didn't run the tests, I also wasn't trying with a vanilla Laravel 6 application... so I'd have to look back into it to provide better information.
