### ISSUE TITLE
Queries are displaying only when retrieving data.

### ISSUE THREAD

**Issue by mertasan** [spatie/laravel-ray#205]
**Describe the bug**

While developing a project, I need to constantly check the db queries with ray.

But Ray expects me to get the data to print the SQL queries.

In other words, I can't see the generated queries without completing most of the project.

**Versions**
- Ray: 1.15.0
- spatie/laravel-ray: 1.23.0

**PHP version:** 8.0.7
**Laravel version:** 8.5.20

**To Reproduce**

1. Go to https://github.com/mertasan/ray-demo
2. Install
3. See `https://[domain].test/make-query` (no results) - [Source code](https://github.com/mertasan/ray-demo/blob/2b79e0acfaa4155d2c3f055e8dde22e10234b35a/app/Http/Controllers/RayController.php#L11-L17)
4. See `https://[domain].test/get-first` (its working) - [Source code](https://github.com/mertasan/ray-demo/blob/2b79e0acfaa4155d2c3f055e8dde22e10234b35a/app/Http/Controllers/RayController.php#L19-L32)
5. See `https://[domain].test/where` (no results) - [Source code](https://github.com/mertasan/ray-demo/blob/2b79e0acfaa4155d2c3f055e8dde22e10234b35a/app/Http/Controllers/RayController.php#L34-L46)

**Expected behavior**

All SQL queries added after the `ray()->showQueries()` function should be displayed in the Ray application.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 11.4 (Big Sur)

**Comment by Nielsvanpach** [comment]
If you don't want to execute your queries, I suggest using `->dump()` and pass that to ray()

```php
ray(DB::table('users')->where('id', 1)->dump());
```

**Comment by mertasan** [comment]
Thanks @Nielsvanpach 

```php
public function build()
{
    $this->joins();
    if($this->search){
        $this->searchQueries();
    }
    if($this->filter){
        $this->filterQueries();
    }
    $this->selectFields();
}
```

In a project that starts as above and consists of dozens of queries, should I do all the queries this way?

How will the proceedings proceed?

If what I want isn't possible, it's ok. But that should not be the path I should follow.

```php
public function getRowsProperty()
{
    return $this->query->paginate($this->getTablePerPage());
}
```

**Comment by Nielsvanpach** [comment]
I'm not sure what your question is.

> All SQL queries added after the ray()->showQueries() function should be displayed in the Ray application.

This only happens if an actual query is executed. If you only want to build queries without executing them, I suggest to dump your query and pass them to Ray manually.
