### ISSUE TITLE
Unable to install in a new Laravel 8 project

### ISSUE THREAD

**Issue by jpscharf** [spatie/laravel-ray#206]
**Describe the bug**
Cannot add to a new Laravel 8 project

**Versions**
Ray version (you can see this in "About Ray"): 1.15.0
spatie/ray: 1.27.1 
spatie/laravel-ray: fails to install 1.23

PHP version: 7.4.18
Laravel version: v8.49.0

**To Reproduce**
1. `laravel new my-project`
2. `composer require spatie/laravel-ray`
3. See error
```
Using version ^1.23 for spatie/laravel-ray
./composer.json has been updated
Running composer update spatie/laravel-ray
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - zbateson/mail-mime-parser 1.3.1 requires guzzlehttp/psr7 ^1.0 -> found guzzlehttp/psr7[1.0.0, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - spatie/laravel-ray 1.23.0 requires zbateson/mail-mime-parser ^1.3.1 -> satisfiable by zbateson/mail-mime-parser[1.3.1].
    - Root composer.json requires spatie/laravel-ray ^1.23 -> satisfiable by spatie/laravel-ray[1.23.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
Found existing alias for "composer". You should use: "c"
```

**Expected behavior**
spatie/laravel-ray installs

**Comment by Nielsvanpach** [comment]
It seems zbateson/mail-mime-parser does not support v2 of guzzlehttp/psr7 yet, as this was released only yesterday.
I've submitted a PR for support: https://github.com/zbateson/mail-mime-parser/pull/173

In the meantime I think you could try to use guzzlehttp/psr7 v1

**Comment by thomasdominic** [comment]
Have you got a tip to install ray without this correction ?

**Comment by Nielsvanpach** [comment]
You could try this

```
composer require --no-update spatie/laravel-ray
composer update -W
```

**Comment by Nielsvanpach** [comment]
Fyi, I've opened a PR for the remaining package to support v2: https://github.com/zbateson/stream-decorators/pull/5

**Comment by thomasdominic** [comment]
Awesome

**Comment by Nielsvanpach** [comment]
@jpscharf this should be fixed now, can you verify?

**Comment by jpscharf** [comment]
@Nielsvanpach Looks like that fixed it. Thank you!
