### ISSUE TITLE
Package "spatie/laravel-ray" is not installed 

### ISSUE THREAD

**Issue by NeptuneDesign** [spatie/laravel-ray#21]
Hello I have a mistake that tells me that I didn't install spatie/laravel-ray when it's a good installation can you help me? Thanks (I'm on windows 10)
https://flareapp.io/share/17Dn1GXm#F12

**Comment by freekmurze** [comment]
The installation instructions are here: https://spatie.be/docs/ray/v1/getting-started/installation-in-laravel

**Comment by NeptuneDesign** [comment]
The installation is already done but I still have this error.
Thanks

**Comment by freekmurze** [comment]
Could you try upgrading to composer v2?

**Comment by NeptuneDesign** [comment]
Thank you that solved the problem, however I had a lot of bugs on the windows software but after a restart of my computer. Everything works fine for the moment. Thank you for the very good work and for your support.
