### ISSUE TITLE
`ray('Date')` and `dump('Date')` cause a TypeError

### ISSUE THREAD

**Issue by bakerkretzmar** [spatie/laravel-ray#221]
### Description

With `spatie/laravel-ray` installed, calling `ray('Date')` or `dump('Date')` causes a TypeError:

```
TypeError: date(): Argument #1 ($format) must be of type string, Spatie\LaravelRay\Ray given
```

### Versions

**Ray version:** N/A, bug is reproducible without the Ray app running

**`spatie/ray` package version:** 1.30.2
**`spatie/laravel-ray` package version:** 1.26.1

**PHP version:** 8.0.10
**Laravel version:** 8.63.0

**Desktop:** M1 mac mini with macOS 11.6 (Big Sur)

### Steps to reproduce

1. `laravel new app && cd app`
2. `composer require spatie/laravel-ray`
3. `php artisan tinker`
4. `ray('date')`
4. See error.

### Expected behaviour

I would expect `ray('date')` and `dump('date')` to both dump the string "date".

**Comment by freekmurze** [comment]
@Nielsvanpach could you take a look at this, I think it's a duplicate for a previous issue.
