### ISSUE TITLE
Error: An object could not be cloned

### ISSUE THREAD

**Issue by genesiscz** [spatie/laravel-ray#222]
**Describe the bug**
I can't connect to server because it says 

![image](https://user-images.githubusercontent.com/1512353/140429824-9233f6d1-061d-49ef-b360-d75c72e29607.png)

(both SSH & password)

**Versions**
Ray version (you can see this in "About Ray"): 1.18.1, just updated after a long time without use on this machine

You can use `composer show` to get the version numbers of:
- spatie/ray package version:
- spatie/laravel-ray package version (if applicable): 

PHP version: 8.0.12
Laravel version: 8.69.0

**Expected behavior**
Connection to host 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1
 
 **Additional context**
I just updated to a new version of macOS so it can be something with this

**Comment by freekmurze** [comment]
Thanks for reporting.

We've received similar reports, and will investigate and fix this very soon.

**Comment by genesiscz** [comment]
Is there a temporary solution, like downgrade or something?

**Comment by genesiscz** [comment]
> Is there a temporary solution, like downgrade or something?

Let me respond to myself, maybe it helps you: Yes, version you download from the download page (at least for Apple Sillicon) is actually v1.17.1 and it works flawlessly.

**Comment by gkimpson** [comment]
I have the same error - I am trying to download an older version for Mac (intel) but unable to do so, the download page only seems to allow me to download the very latest version - can anyone help?

**Comment by AdrianMrn** [comment]
My bad, releasing a fix now!
