### ISSUE TITLE
Unable to change the private key path when adding a new server

### ISSUE THREAD

**Issue by gkimpson** [spatie/laravel-ray#223]
**Describe the bug**
When 'adding server' to Ray I am unable to change the 'Private key path' with a different filename and save - the default path is `~/.ssh/id_rsa` but when I change this and click save and return back to it I still see the default path.

**Versions**
Ray version : 1.18.2

**To Reproduce**
1. Go to 'Servers' in the top right corner (purple button with 3 white lines)
2. Click on 'Add Server'
3. Enter your server info & try to change the default private key path
4. Click save
5. Re-open the same server by clicking the edit button and you will notice the private key path doesn't appear to have changed

**Expected behavior**
Should be able to change the private key path

**Screenshots**
![image](https://user-images.githubusercontent.com/850218/140495471-d8fd4060-17a5-48f1-9e52-3ce06e614f14.png)

**Desktop (please complete the following information):**
 - OS: MacOS BigSur
 - Version 11.6

**Comment by AdrianMrn** [comment]
Thanks for the detailed report! I'm releasing a fix for this bug now in 1.18.3, it should be online in about 15 minutes.
