### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by ulfie22** [spatie/laravel-ray#28]
On the 

Usage -> In Laravel

page, there is a reference to a function called **stopLoggingQueries** . In the example following, it is shown as ** stopShowingQueries**. My guess is the name of this function changed during development. 

Thanks for the super cool tool!!

**Comment by erdiegoant** [comment]
Which version of the package did you install?

**Comment by freekmurze** [comment]
I've fixed this in our docs.

If you see more strange things, click to edit button on top of the page to create an issue.
