### ISSUE TITLE
Open With VSCODE prompt

### ISSUE THREAD

**Issue by Abdullah-Hejazi** [spatie/laravel-ray#29]
Hi there
Whenever I click the ray link to open it in VSCODE, it always shows me this prompt.
I know it's vscode related, but is there a way to ALWAYS accept ?

![1](https://user-images.githubusercontent.com/46539561/103959654-273e1b00-5105-11eb-8fca-e97b7ef9c5d0.PNG)

**Comment by riasvdv** [comment]
Unfortunately we can't do anything about that, there seems to be an issue open at VSCode that addresses this: https://github.com/microsoft/vscode/issues/95670
