### ISSUE TITLE
InstalledVersion does not detect spatie/laravel-ray as being installed

### ISSUE THREAD

**Issue by CrixuAMG** [spatie/laravel-ray#30]
Running the latest version of Laravel Ray, Laravel 8.21.0 on a MacBook Pro, any attempt so far has given me the same response. The package is installed, exists within the vendor/spatie folder and is listed in the composer.json and composer.lock file.

Below I included the exception and first trace

```
{
  "message": "Package \"spatie/laravel-ray\" is not installed",
  "exception": "OutOfBoundsException",
  "file": "/Users/christian/Code/project/vendor/composer/composer/src/Composer/InstalledVersions.php",
  "line": 110,
  "trace": [
    {
      "file": "/Users/christian/Code/project/vendor/spatie/laravel-ray/src/Ray.php",
      "line": 149,
      "function": "getVersion",
      "class": "Composer\\InstalledVersions",
      "type": "::"
    },
}
```

**Comment by freekmurze** [comment]
This will be solved by upgrading to composer 2.

**Comment by CrixuAMG** [comment]
This indeed solved my issue, thank you!
