### ISSUE TITLE
Wrong formatted sql in Ray when using text search operator @@ in postgres query

### ISSUE THREAD

**Issue by pablosebastianr** [spatie/laravel-ray#303]
**Describe the bug**
The formatted sql query shown when using the text search operator "@@" in postgres is wrong, it gets transformed into "@ @" which is incorrrect

**Versions**
Ray version (you can see this in "About Ray"): 2.5.1.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.37.2
- spatie/laravel-ray package version: 1.32.4  

PHP version: 8.1
Laravel version: 9.52.7

**To Reproduce**
 ```php
\DB::select("select to_tsvector('simple', 'some text') @@ to_tsquery('simple', 'text') as field");
```

**Expected behavior**
```sql
select
  to_tsvector('simple', 'some text') @@ to_tsquery('simple', 'text') as field
```

**Screenshots**

![laravel-ray-bug](https://github.com/spatie/laravel-ray/assets/39702392/28bea4d3-4738-4144-bdd4-ebfb27ec701d)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Sam-Apostel** [comment]
Hi @pablosebastianr 

Version 2.6.5 of the Ray app will now try different sql dialects, including postgresql.

I'm closing this issue now but if you run into more formatting issues, feel free to tag me.
