### ISSUE TITLE
Parse Error in Ray.php line 15

### ISSUE THREAD

**Issue by ConorAAG** [spatie/laravel-ray#31]
Installed ray v1.1.1 and laravel-ray v1.1.0

The app is open and I have placed a simple call, ray('hello world'), in one of my controllers. It fails and the following is dumped in my log file.

[2021-01-08 08:15:07] local.ERROR: syntax error, unexpected 'bool' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) {"userId":21094,"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'bool' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) at C:\\...\\vendor\\spatie\\laravel-ray\\src\\Ray.php:15)
[stacktrace]
#0 C:\\...\\vendor\\composer\\ClassLoader.php(322): Composer\\Autoload\\includeFile('C:\\\\...')
#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Spatie\\\\LaravelR...')
#2 [internal function]: spl_autoload_call('Spatie\\\\LaravelR...')
#3 C:\\...\\vendor\\spatie\
ay\\src\\helpers.php(15): class_exists('Spatie\\\\LaravelR...')
#4 C:\\...\\app\\Http\\Controllers\\MasterDataController.php(53): ray('hello world')

**Comment by riasvdv** [comment]
Please make sure you're running Ray on PHP7.4 or higher

https://freek.dev/1598-how-to-check-which-version-of-php-you-are-running

**Comment by freekmurze** [comment]
A syntax error makes me things that you did not have the right PHP version available.
