### ISSUE TITLE
Livewire v3: ray($component) shows the rendered HTML

### ISSUE THREAD

**Issue by levu42** [spatie/laravel-ray#312]
**Describe the bug**
In Livewire v3, outputting a component doesn't show the class info but instead renders the component's HTML and shows that in ray.

**Versions**
Ray version (you can see this in "About Ray"): 2.6.5

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.37.2
- spatie/laravel-ray package version (if applicable): 1.32.6

PHP version: 8.2.9
Laravel version: 10.20.0
Livewire version: 3.0.1

**To Reproduce**
1. Create a new project with Livewire v3
2. E.g. inside a component, in a function called by a button click in the browser, put `ray($this)`
3. See the rendered HTML inside ray

**Expected behavior**
See the normal class overview, e.g. state of the component etc

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Comment by riasvdv** [comment]
This is fixed in the underlying spatie/ray package: https://github.com/spatie/ray/releases/tag/1.37.4
