### ISSUE TITLE
ray(Illuminate\Validation\ValidationException) doesn't display anything

### ISSUE THREAD

**Issue by levu42** [spatie/laravel-ray#316]
**Describe the bug**
trying to display an Illuminate\Validation\ValidationException doesn't display anything. Doing a `ray('a'); ray($exception); ray('b');` just shows `a` and `b`. `ray([$exception])` works however.

**Versions**
Ray version (you can see this in "About Ray"): 2.6.9

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.38.0
- spatie/laravel-ray package version (if applicable): 1.33.0

PHP version: 8.2.10
Laravel version: 10.23.1

**To Reproduce**
```
try {
  $this->validate();
} catch (\Throwable $e) {
  rd($e);
}
```

**Actual output**
None

**Expected behavior**
I expect to see the ValidationException in ray

**Screenshots**

**Desktop (please complete the following information):**
 - OS: arch linux
 - Version: (newest)

**Comment by levu42** [comment]
One thing I noticed when trying to use `var_dump`, `print_r` or `var_export` on the request I tried dumping: there seems to be a circular reference in its class members. Could that be part of the reason why ray is having problems displaying that object?

**Comment by keithbrink** [comment]
I also am having similar issues where Ray silently ignores any classes with circular references. Can this issue be re-opened?

**Comment by timvandijck** [comment]
@levu42 no problem, I'm sorry we lost track of this.

@keithbrink I'll have a look at it. Could you share your package and PHP versions and OS?

**Comment by keithbrink** [comment]
Sure thing: PHP 8.3.1, MacOS, Ray Desktop app: 2.7.5

Composer: spatie/laravel-ray@1.35.1, spatie/ray@1.41.1

**Comment by keithbrink** [comment]
@timvandijck This is still an issue.
