### ISSUE TITLE
Ray seems not be running at http://localhost:23517

### ISSUE THREAD

**Issue by lukesnowden** [spatie/laravel-ray#32]
Hi, nice looking package!

I'm having trouble getting it up and running. When calling `ray()` I'm receiving the error `Ray seems not be running at http://localhost:23517`.

Any reason why I'd be getting this error?

Thanks!

**Comment by freekmurze** [comment]
I can't seem to reproduce this. Would you mind recreating this issue at the spatie/ray repo using the issue template? Make sure to include version numbers and such. Thanks!

**Comment by lukesnowden** [comment]
I think it's because I'm running through Docker. Is there any documentation around this? Thanks in advance!

**Comment by freekmurze** [comment]
I don't have much experience with Docker myself, but other users are investigating:

https://github.com/spatie/ray/pull/41/files

**Comment by chriischambers** [comment]
I'm getting this issue in CI running my tests.

There was 1 error:
1) Tests\Feature\Http\Controllers\Auth\LoginControllerTest::updating_a_legacy_password_to_bcrypt
Exception: Ray seems not be running at http://localhost:23517

**Comment by lukesnowden** [comment]
> I'm getting this issue in CI running my tests.
> 
> There was 1 error:
> 
> 1. Tests\Feature\Http\Controllers\Auth\LoginControllerTest::updating_a_legacy_password_to_bcrypt
>    Exception: Ray seems not be running at http://localhost:23517

Maybe call `ray()->disable()` in test setup?

**Comment by lukesnowden** [comment]
```
$ray = new Ray($settings, $client);

if (! $settings->enable) {
    $ray->disable();
}
```

Seems like the `Client` will be invoked even if it is `->disabled()`. 

Try changing `Spatie\LaravelRay` to 

```
if (! $settings->enable) {
    $ray = new Ray($settings, $client);
    
    $ray->disable();
}
```

to test.

**Comment by freekmurze** [comment]
@chriischambers This is fixed in the latest release.
