### ISSUE TITLE
Bug on ray dependency

### ISSUE THREAD

**Issue by allanmcarvalho** [spatie/laravel-ray#339]
**Describe the bug**
A dependency from laravel ray is crashing the feature tests.
Is expected that `./vendor` comes on 0 index from method `ClassLoader::getRegisteredLoaders()`, but came `/vendor/rector/rector/vendor` instead. `./vendor` came on index 1, but laravel use index 0 to start application.

**Versions**
Ray version: 1.36.0

PHP version:
Laravel version: 8.3.4

**To Reproduce**
1 Running Laravel Feature Tests (Require application start) using pest

**Expected behavior**
No fail Feature tests

**Screenshots**
![Captura de Tela 2024-04-06 às 11 34 03](https://github.com/spatie/laravel-ray/assets/12012197/40653331-780a-4889-b1e5-05bb11b28908)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] macOS
 - Version [e.g. 22] Sonoma 14.4.1
 
 **Additional context**
This problem started today after a composer update command. Deleting rector vendor folder, the problems it's solved.

**Comment by timvandijck** [comment]
@allanmcarvalho I asume 8.3.4 is the PHP version and not the Laravel version? Could you share your Laravel version too?

**Comment by allanmcarvalho** [comment]
Hi, I really missed some contexts.

On tests fail on PHP 8.3.4
![Captura de Tela 2024-04-08 às 10 46 02](https://github.com/spatie/laravel-ray/assets/12012197/0273e949-c2dd-412a-970a-5fcb80b6443a)

On local machine fails on Herd PHP 8.3.3
![Captura de Tela 2024-04-08 às 10 49 22](https://github.com/spatie/laravel-ray/assets/12012197/9a37eecd-8f41-4b84-a366-66c35c6ec068)

**Comment by allanmcarvalho** [comment]
If I remove all spatie dependencies that need `rector/rector` tests will pass.

I tried remove and works
```
        "spatie/laravel-data": "^4.5.0",
        "spatie/laravel-ray": "^1.36.0",
```

**Comment by timvandijck** [comment]
@allanmcarvalho I tried to replicate your problem but I was not succesfull. I'm also not quite sure how we could cause this issue.

If are able to create an example project on git that has the problem I would be happy to dig further into it.

**Comment by allanmcarvalho** [comment]
The problems stopped for me. I don't know what the reason. I only updated my composer dependencies and updated Herd PHP from 8.3.3 to 8.3.4.

I made the same previous steps that was failed (delete vendor folder and install again) and now its working.

I appreciate your time, now appears to be solved

**Comment by timvandijck** [comment]
@allanmcarvalho good to hear!
