### ISSUE TITLE
what if the ray desktop app is not running

### ISSUE THREAD

**Issue by michabbb** [spatie/laravel-ray#34]
hi, I would like to ask: in some projects, it´s not uncommon to use some debug outputs in the code and don´t remove them. because they provide some interesting info. so let's say you work in a small team within one project, some people are using ray, some not. so when you add "ray()" in some situations and let this in, even in production, is there an option to tell ray that there is no app running so instead of trying to connect the app, that will end in a timeout (i guess) because the app is not running, it should behave more like a "print_r" and shouldn´t search for the app in the first place? so for example, the ray config inside code would have a switch like "env=debug" or "env=produktion" and only if "env=debug" ray will try to connect to the app and in all other cases it wouldn´t even try because it knows, there is no app running?

**Comment by freekmurze** [comment]
We will handle this by not doing throwing an exception when it is not running.

**Comment by michabbb** [comment]
but how do i prevent any timeouts or even trying to connect to the app at all ?

**Comment by ju5t** [comment]
Not sure about the timeouts. But I do know you can disable it in `ray.php`, see: https://spatie.be/docs/ray/v1/getting-started/configuring-ray. If you scroll down you will see:

```php
    /*
     * This settings controls whether data should be sent to Ray.
     *
     * By default, `ray()` will only transmit data in non-production environments.
     */
    'enable' => true,
```

It's probably useful to link that to a setting you already have or to create a new environment variable for it. That's up to you.

**Comment by ju5t** [comment]
I did some source diving. In the client there is a timeout of 2 seconds. I tested this by closing the Ray app and rerunning the request (it's inside a Livewire component). It needed 169ms. For some reason it's not even close to the timeout.
