### ISSUE TITLE
path mapping needed + phpstorm not found

### ISSUE THREAD

**Issue by michabbb** [spatie/laravel-ray#35]
most projects believe, there exists only mac or Linux and virtualization is - sadly - never an issue.
windows users often use virtualization to let code run 100% within Linux, like in my case.
so code is running on a Linux host within docker. so of course, paths on Linux or inside docker
has nothing todo with the paths my windows-phpstorm is using. so when `ray('hello word')` send
the file and path to the desktop app, the path needs to be mapped to the local windows path
to make it working with phpstorm. ray on windows shows me of course the path that is used
inside docker (in my Linux host), so for instance `/home/blabla/something.php` and on windows
the real path is `C:\blabla\something.php` 😏 

clicking on the file link within windows says (translated) something like: you need to install a new app to open this phpstorm link.

**Comment by michabbb** [comment]
besides that: I have put `ray()` inside a file somewhere in my project but the app shows the `vendor/..../helpers.php`,
is that meant to be? so i don´t see the real file i have put my debug in, instead i see this.

![image](https://user-images.githubusercontent.com/3524595/104012871-dd127380-51b0-11eb-83fa-1f42207f3520.png)

**Comment by SebastiaanKloos** [comment]
> besides that: I have put `ray()` inside a file somewhere in my project but the app shows the `vendor/..../helpers.php`,
> 
> is that meant to be? so i don´t see the real file i have put my debug in, instead i see this.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/3524595/104012871-dd127380-51b0-11eb-83fa-1f42207f3520.png)
> 
> 

My project too. It's in a class based of a ServiceProvider (October CMS plugin Plugin.php in the boot function)

**Comment by freekmurze** [comment]
Path mapping was added in the latest version. You can use the `remote_path` and `local_path` settings to fix this.

**Comment by michabbb** [comment]
@freekmurze both problems still exist, even with your latest update 1.0.5.0: ray does not show me my own file, it still shows "helpers.php:28"
and no path gets mapped.

so ray is sending:

```json
{
   "uuid":"f1301a43-066e-401c-a2e3-e3a7ada2687a",
   "payloads":[
      {
         "type":"log",
         "content":{
            "values":[
               "hello world"
            ]
         },
         "origin":{
            "file":"\/home\/xxxxxxx\/yyyyyyy\/vendor\/spatie\/ray\/src\/helpers.php",
            "line_number":28
         }
      }
   ],
   "meta":{
      "php_version":"7.4.9",
      "php_version_id":70409,
      "ray_package_version":"1.3.2.0"
   }
}
```

but file should be: `C:\\xxxxx\\yyyy\\` and so on....

my `ray.php`:

```php
<?php
return [
    /** only the important part */
    'remote_path' => '/home/xxxxxxxxx/yyyyyyyyy/',
    'local_path' => 'C:\\\\vm\\data\\xxxxxxx\\yyyyyyyy\\'
];
```

and opening phpstorm still does not work:

![image](https://user-images.githubusercontent.com/3524595/104047532-131c1b80-51e2-11eb-90f6-e4b8fa7f2aef.png)

**Comment by michabbb** [comment]
🖕
