### ISSUE TITLE
Laravel Vapor Issues

### ISSUE THREAD

**Issue by polbatllo** [spatie/laravel-ray#36]
Hello and thank you for an awesome product.

It is mentioned here that it is preferred to add Laravel Ray as a normal dependency rather than a `--dev` one: https://spatie.be/docs/ray/v1/getting-started/installation-in-laravel

This makes total sense, but this won't my experience is that some things fail there and ray actually does start.
https://sentry.io/share/issue/181f7a8d1e28440b85956d6a7bc76ea2/

**Comment by freekmurze** [comment]
This has been fixed in v1.3.2. Open up an new issue if this still gives problems in that version. (I've just added a new issue template).
