### ISSUE TITLE
Unable to install when running PHPStan 2.x.

### ISSUE THREAD

**Issue by neoighodaro** [spatie/laravel-ray#366]
**Describe the bug**
Unable to install when running PHPStan 2.x.

**Versions**
Ray version (you can see this in "About Ray"): 1.x

PHP version:
Laravel version: N/A

**To Reproduce**
1. Try to install on any project running PHPStan 2.x

**Expected behavior**
The composer installation succeeds
 
 **Additional context**
PHPStan needs to be updated in the package

**Comment by sweptsquash** [comment]
This is related to the `rector/rector` package there's an open issue regarding PHPStan 2.0 which can be found here with their latest update https://github.com/rectorphp/rector/issues/8815#issuecomment-2493467044

**Comment by sweptsquash** [comment]
> I reaaaally want that corresponding PR to happen - but unfortunately, the spatie team seems to be very busy.
> 
> Is there anything I can do to help?

@ahoiroman completely understand I'm there with you but we're currently waiting on the stable tagged release for reactor 2.0. Currently 2.0 RC1 was released around 20 hours ago https://github.com/rectorphp/rector/issues/8815#issuecomment-2504535522 so we need to wait for the stable version to be published before we can ask Spatie to fully review and merge these PRs in.
