### ISSUE TITLE
Exception if Ray not open

### ISSUE THREAD

**Issue by colinhall17** [spatie/laravel-ray#37]
Environment: Windows using Homestead

If the Ray app is not open and the project has spatie/laravel-ray as a dependency, if you hit any exception the following exception will be displayed instead of the actual Exception.

`Ray seems not be running at http://10.0.2.2:23517`

This can be changed by setting 'send_log_calls_to_ray' => false

But I'm wondering if it would be better to see if it is a log and if so don't throw the not running exception?

**Comment by colinhall17** [comment]
Of course the other option is that you open Ray, but I'm thinking that you could be collaborating with another developer who doesn't have Ray.  Then the exceptions are going to be meaningless.

**Comment by freekmurze** [comment]
Yeah, if Ray isn't open, there shouldn't be an exceptions, I'll look into this.

**Comment by freekmurze** [comment]
This has been fixed in Ray 1.3.1
