### ISSUE TITLE
is_dir(): open_basedir restriction in effect. File(/data/sites/web) is not within the allowed path(s):

### ISSUE THREAD

**Issue by vdvcoder** [spatie/laravel-ray#40]
**Versions**
spatie/ray (1.3.2)
spatie/laravel-ray (1.3.0)

You can use `composer show` to get the version numbers of:
- spatie/ray package version:
- spatie/laravel-ray package version (if applicable): 

PHP version:
7.4

**Steps to reproduce the behavior:**
1. nstall spatie/laravel-ray (locally)
2. Test locally -> works perfect
3. git add , git commit, git push
4. On staging server, git pull
5. Reload website:  **is_dir(): open_basedir restriction in effect. File(/data/sites/web) is not within the allowed path(s):**

I use a shared hosting.

OS: macOS Catalina
Version: version 10.15.7
![screenshot (1)](https://user-images.githubusercontent.com/13916116/104033252-94b67e00-51cf-11eb-875b-52d73f996f5a.png)

**Comment by vdvcoder** [comment]
![Uploading screenshot (2).png…]()

**Comment by vdvcoder** [comment]
![screenshot (2)](https://user-images.githubusercontent.com/13916116/104033908-7604b700-51d0-11eb-94ac-da8f7d67b310.png)

**Comment by patinthehat** [comment]
Ending the recursive parent directory search in `SettingsFactory::searchConfigFiles()` once the current project's root (where `./vendor` exists) has been reached without finding a config file should resolve the issue.

Thoughts?

**Comment by freekmurze** [comment]
This has been fixed in the latest version of spatie/ray.
