### ISSUE TITLE
select all + delete does not work

### ISSUE THREAD

**Issue by michabbb** [spatie/laravel-ray#41]
**Describe the bug**

Inside the Ray Electron app:
Menu: Edit -> Select all (STRG+A) then, Menu: Edit -> Delete, does nothing
"Select All" does not select the individual dumps, it only selects the whole text on that electron-page.
the whole menu item "Edit" seems to be useless here, because it looks like that "Copy" is the only item
that has a useful function here. but we all know the hotkey for "copy" so maybe the menu item "Edit"
can be removed in that app?

anyway... I would like to know how I am able to delete the entries ;)

**Versions**
1.0.5.0

**Expected behavior**
delete all dumps on the current page

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by freekmurze** [comment]
I don't consider this a bug. We didn't intend to allow content updates by users. We might add this in the future.

**Comment by michabbb** [comment]
so in the meantime you prefer to let stay a menu in the game without any sense, wow, you really know how to motivate to help you.

for a software full of bugs (I know it's new), it costs a lot of time, testing, beside you, I don't get paid for this "selfless help" - and your way of paying this back is closing every issue with one simple sentence.

👍

**Comment by Bouhnosaure** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/3416579/104338325-ad3bd680-54f6-11eb-8d66-640d05a9a1b8.jpg)

![Screenshot_3](https://user-images.githubusercontent.com/3416579/104338539-ea07cd80-54f6-11eb-9af5-2ceda9ef3a96.jpg)

Indeed, it would be useful to delete logs... now the app is slow as hell 😅 clearing out shouldn't be an exotic feature request

**Comment by freekmurze** [comment]
@AdrianMrn we should probably set a limit on the amount of items we keep in memory. Can be set to a high number by default.

**Comment by Bouhnosaure** [comment]
Thanks @freekmurze, for taking this in consideration.

Also i could be interesting either be able to manually set a limit in the settings menu or add a button to clear all the things in memory ( kind of a failsafe ).

This is a great tool 😄 !

**Comment by AdrianMrn** [comment]
I've created a separate issue for this: https://github.com/spatie/laravel-ray/issues/86
