### ISSUE TITLE
Does not open Links to Files in Sublime

### ISSUE THREAD

**Issue by chellmann** [spatie/laravel-ray#42]
When clicking in Ray on a Link to a File and Line, the File is not Opened in Sublime Text.
In Rays Settings, "Editor" is set to "Sublime"

**Versions**
Ray version:1.0.5
Sublime: 3.2.2, 3211
Mac Os: 10.15.7

**Comment by freekmurze** [comment]
It seems that you must manually register the subl protocol to get this to work: https://twitter.com/freekmurze/status/1347646538525368320
