### ISSUE TITLE
Dead Page and Question

### ISSUE THREAD

**Issue by mikeerickson** [spatie/laravel-ray#44]
This is a dead page -- https://github.com/spatie/laravel-ray/discussions/new?category=q-a

Further, to my question, if `ray` is not running, I am thinking that code should continue and not throw an error?  Is this not the case?

**Comment by freekmurze** [comment]
Thanks for letting me know. I forgot to enable discussions, and have just fixed that. The link is now work.

If the Ray app is not running, it indeed shouldn't throw an exception, I've made some improvements around this in the latest version of the spatie/ray package.

If it does throw an exception for you, could you open a new issue, and mention all the versions you are using, a track trace would also be very helpful in that case.

I do hope you'll enjoy using Ray!
