### ISSUE TITLE
OutOfBoundsException    Package "spatie/laravel-ray" is not installed

### ISSUE THREAD

**Issue by jongravois** [spatie/laravel-ray#53]
I installed Version 1.0.8 (1.0.8) of Ray.

I required it with composer using ```composer require spatie/laravel-ray``` and ran the "My first ray call" -- no problems and worked beautifully.

I pushed the commit to production.

I ran an artisan command in production and received this error:
```
OutOfBoundsException

  Package "spatie/laravel-ray" is not installed

  at vendor/composer/composer/src/Composer/InstalledVersions.php:110
    106▕      */
    107▕     public static function getVersion($packageName)
    108▕     {
    109▕         if (!isset(self::$installed['versions'][$packageName])) {
  ➜ 110▕             throw new \OutOfBoundsException('Package "' . $packageName . '" is not installed');
    111▕         }
    112▕
    113▕         if (!isset(self::$installed['versions'][$packageName]['version'])) {
    114▕             return null;

      +11 vendor frames
  12  [internal]:0
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleException()
forge@production-uam:~/avtechnix.com$  OutOfBoundsException
OutOfBoundsException: command not found
```
I ran dump-autoload in production and error re-appeared.

I ran ```COMPOSER_MEMORY_LIMIT=-1 composer require spatie/laravel-ray``` in production, dumped auto-load and had same error.

What else can I do to silence this stoppage and error ... i **need** to run this artisan command.

**Comment by freekmurze** [comment]
Could you try to upgrade to composer 2?

**Comment by jongravois** [comment]
Already there — Composer version 2.0.3 2020-10-28 15:50:55

**Comment by freekmurze** [comment]
Does `composer show` on your server show the laravel-ray package?

**Comment by jongravois** [comment]
YES

spatie/backtrace                                 1.0.0    A better backtrace
spatie/eloquent-sortable                         3.10.0   Sortable behaviour for eloquent models
spatie/image                                     1.10.1   Manipulate images with an expressive API
spatie/image-optimizer                           1.3.2    Easily optimize images using PHP
spatie/laravel-dashboard                         2.0.1    A dashboard for Laravel
spatie/laravel-dashboard-time-weather-tile       2.0.1    A tile for Laravel Dashboard that displays the time and ...
spatie/laravel-medialibrary                      9.4.1    Associate files with Eloquent models
spatie/laravel-medialibrary-pro                  1.12.2   Handle media in a Laravel app
spatie/laravel-model-status                      1.10.2   A package to enable assigning statuses to Eloquent Models
spatie/laravel-permission                        3.18.0   Permission handling for Laravel 5.8 and up
—> spatie/laravel-ray                               1.3.1    Easily debug Laravel apps
spatie/laravel-tags                              3.0.1    Add tags and taggable behaviour to your Laravel app
spatie/laravel-translatable                      4.6.0    A trait to make an Eloquent model hold translations
spatie/macroable                                 1.0.1    A trait to dynamically add methods to a class
spatie/ray                                       1.3.5    Debug with Ray to fix problems faster
spatie/sun                                       1.1.1    Get information on the position of the sun
spatie/temporary-directory                       1.3.0    Easily create, use and destroy temporary directories

**Comment by freekmurze** [comment]
Then I don't know... You should investigate on your server why composer doesn't recognise laravel-ray being installed.

If you find the cause, let me know, this might help other users. If you find there's anything the package can do, to avoid this problem let me know.

If you can reproduce the error, I'd appreciate to an example app where I can see the problem locally.

**Comment by jongravois** [comment]
Jon === Stupid

Composer ON SERVER was version 1.X

All Good Now!!!

Jon

**Comment by freekmurze** [comment]
Glad you could find the solution! 👍
