### ISSUE TITLE
local_path option is not recognized with WSL2 & Laravel Sail

### ISSUE THREAD

**Issue by oliverhermanni** [spatie/laravel-ray#61]
**Describe the bug**
The local_path option is not recognized on WSL 2 using Laravel Sail. The path returned is from the Docker container, not my local path.

I asked the question in the discussion, but decided to move it here to report it as an issue.

**Versions**
Ray version: 1.3.4
PHP version: 8.0.0
Laravel version: 8.21.0

**Expected behavior**
A click on the Goto Line in the desktop ray app should show the line in my editor

**Desktop (please complete the following information):**
 - OS: Windows 10 with WSL 2
 
 **Additional context**
Although the guy who reported this first had questionable manners, he seems to have a valid point. It's not a breaking bug though, I'm still happy with ray.

**Comment by freekmurze** [comment]
Thanks for reporting this. 

I'm having a hard time reproducing this and I hope you can help debug a little. 

The path is being corrected in [this function](https://github.com/spatie/ray/blob/6fb4f6eef6fe2ce1c58f9b831a004d73cfa88607/src/Payloads/Payload.php#L17-L24).

Could you check if the `$this->remotePath` and  `$this->localPath` are set to the values you've set in your configuration?

Please make sure you are using the latest version of laravel-ray.

**Comment by oliverhermanni** [comment]
$this->localPath returns `/D:\Projects\Laravel\my_project`. Note the leading slash.

**Comment by freekmurze** [comment]
If you trim away that slash there, does it work?

Of course, I'll try to fix it in a better why, but it would be helpful to know that fixing that local path with fix the problem.

**Comment by oliverhermanni** [comment]
Oh, sorry. That was not true! $this->localPath returns `D:\Projects\Laravel\my_project`. The slash is only seen in the desktop app. But at least the path is shown, clicking does not work, though.

**Comment by freekmurze** [comment]
So it displays the right path, but only clicking does not work?

**Comment by oliverhermanni** [comment]
I'm using PhpStorm. I digged some more into this problem and found out, that Windows does not support the PhpStorm protocol. It's possible to fix this by using [this](https://github.com/aik099/PhpStormProtocol), which was also mentioned on [Laracasts](https://laracasts.com/discuss/channels/general-discussion/cant-get-ignition-to-open-file-in-phpstorm). Maybe it's worth to add this to the docs under Questions and issues?

When I click on the link now, PhpStorm tells me that the path is invalid, because of the slash, though. Probably the desktop app needs to be fixed for that.

![image](https://user-images.githubusercontent.com/1240179/104206283-9ed6b780-542f-11eb-8f2a-73d426a1ca89.png)

**Comment by freekmurze** [comment]
@AdrianMrn does the Ray app add that `\` in the `EditorURL`?

**Comment by oliverhermanni** [comment]
Note: in the Ray app it's shown as a `/`, PhpStorm display a `\`.

**Comment by AdrianMrn** [comment]
@freekmurze No, only the path that is sent from the application is used.

**Comment by freekmurze** [comment]
@oliverhermanni 

> $this->localPath returns `/D:\Projects\Laravel\my_project`.

I'm trying to figure out where that `/` comes from. What is the value of `local_path` in your config?

**Comment by oliverhermanni** [comment]
Here's my full config

```
<?php

return [
    'enable' => true,
    'send_log_calls_to_ray' => true,
    'send_dumps_to_ray' => true,
    'host' => 'host.docker.internal',
    'port' => 23517,
    'remote_path' => 'var/www/html',
    'local_path' => 'D:\Projects\Laravel\myproject',
];
```

**Comment by oliverhermanni** [comment]
Oh, there's a missing `/` in `'remote_path'`! That is where it's coming from! :D Everything is working now!

**Comment by oliverhermanni** [comment]
Well, I reopen this, because of the phpstorm protocol. This information really should be added to the docs.

**Comment by freekmurze** [comment]
Could you open up a new issue dedicated for that PhpStorm protocol problem? I think it's a bit confusing to have a single issues address... multiple issues 🙂

**Comment by oliverhermanni** [comment]
I will. Thanks for your help and patience! And for ray of course. :)
