### ISSUE TITLE
ExecutedQueryPayload time should display as milliseconds

### ISSUE THREAD

**Issue by ejunker** [spatie/laravel-ray#63]
**Describe the bug**
The queries that are logged show the Time as μs when it should be milliseconds.

https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Events/QueryExecuted.php#L22
```php
    /**
     * The number of milliseconds it took to execute the query.
     *
     * @var float
     */
    public $time;
```

**Versions**
Ray version (you can see this in "About Ray"): 1.2.0

You can use `composer show` to get the version numbers of:
- spatie/ray package version:
- spatie/laravel-ray package version (if applicable): 

PHP version: 7.4
Laravel version: 8.21.0

**To Reproduce**
1. log a query

**Expected behavior**
time is shown with 'ms'  suffix

**Screenshots**
<img width="206" alt="image" src="https://user-images.githubusercontent.com/4758/104220966-daf52280-5405-11eb-8972-39821d6a3ab9.png">

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] macOS
 - Version [e.g. 22] 10.15.7
 
 **Additional context**

**Comment by freekmurze** [comment]
Thanks for reporting.

This will be fixed in upcoming version of Ray 1.2.2 which will be released soon.
