### ISSUE TITLE
WSL 2 + Docker + VSCode - file references open in new VSCode window instead of in existing one

### ISSUE THREAD

**Issue by khromov** [spatie/laravel-ray#68]
**Describe the bug**
I'm trying to make it possible to click on a file link in Ray and have VSCode open it. I'm running it using Windows 10, WSL 2 + the official Docker integration as well as the official VSCode ["Remote WSL"](https://code.visualstudio.com/blogs/2019/09/03/wsl2) extension.

This means that VSCode runs inside the WSL distro (in my case Ubuntu 20.04) and then sends all data to the VSCode GUI remote which is running on Windows 10.

I understand that it sounds a bit confusing, but I almost got it to work.

The path rewrites work correctly, however, every time I click on a file name in Ray, it **opens a new VSCode window instead of opening the file in the already opened one**. This might be a VSCode/WSL2 limitation but it does make using Ray a bit of a pain, so I'm hoping someone could look into this or if there is any approach that would make this work as expected.

My configuration is as follows:

```php
<?php
return [
    'host' => 'host.docker.internal',
    'port' => 23517,
    /* This is the root path inside the Docker container */
    'remote_path' => '/var/www/html/',
    /* This is the WSL NFS path that corresponds to the root of the Docker container */
    'local_path' => '\\wsl$\\Ubuntu-20.04\\home\\k\\GitHub\\php8\\src-compose\\',
];
```

**Versions**
Ray version (you can see this in "About Ray"): 1.2.2.0

You can use `composer show` to get the version numbers of:
WP plugin version: 

PHP version: 8.0
Laravel version: N/A

**To Reproduce**
1. Install Docker, VSCode, WSL 2 and a WSL 2 distro & the Windows version of Ray on Windows 10.
2. Install the WSL Remote extension in VSCode.
3. Activate the Docker WSL2 support in Docker options.
4. Run a PHP application that has Ray installed inside Docker (I'm using [this image](https://hub.docker.com/r/khromov/alpine-nginx-php8))
5. Configure the project in a similar way to my `ray.php` (paths will have to be adjusted)
6. Try to log something and then open the file definition under the log entry.
7. The file opens in a new VSCode instance.

**Expected behavior**
See earlier text.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10

 **Additional context**
N/A

**Comment by freekmurze** [comment]
@AdrianMrn weren't we already tracking this one elsewhere?

**Comment by JustSteveKing** [comment]
I am having the same issues, I will be about during business hours today to help debug this if additional help is required

**Comment by AdrianMrn** [comment]
[I investigated this issue yesterday](https://github.com/spatie/ray/issues/16) and it doesn't seem like we can fix it on our end, unless I missed something major. Feel free to chip in if I've missed anything, and I'll gladly reopen the issue!

**Comment by JustSteveKing** [comment]
Thanks @AdrianMrn I will check the issue you linked and see what I can make of it too.

**Comment by IAmRGroot** [comment]
@JustSteveKing did you ever find a way to make the links open in (an already opened) VSCode Docker Container window?

I'm still experiencing the same issue where the Windows WSL path opens a new window

**Comment by JustSteveKing** [comment]
> @JustSteveKing did you ever find a way to make the links open in (an already opened) VSCode Docker Container window?
> 
> I'm still experiencing the same issue where setting the local_path to the Windows WSL path opens a new window

I'm not sure if you tagged the right person here, I don't use WSL2 🙃

**Comment by IAmRGroot** [comment]
> > @JustSteveKing did you ever find a way to make the links open in (an already opened) VSCode Docker Container window?
> > I'm still experiencing the same issue where setting the local_path to the Windows WSL path opens a new window
> 
> I'm not sure if you tagged the right person here, I don't use WSL2 🙃

Whoops I meant to tag OP
