### ISSUE TITLE
Ray processes keep running after closing

### ISSUE THREAD

**Issue by GraxMonzo** [spatie/laravel-ray#7]
![image](https://user-images.githubusercontent.com/11737104/103916159-4b662000-5136-11eb-96d7-d2e9675174fc.png)

**Comment by freekmurze** [comment]
Thanks for reporting! We'll fix this soon. 

So, after trying to quit the app, it still is running?

**Comment by GraxMonzo** [comment]
It's closed but processes are active. System tray are clear

**Comment by GraxMonzo** [comment]
This problem was partially resolved by changing `Show app` preference to `On both task bar and system tray`. Closing Ray from system tray kills all processes

**Comment by freekmurze** [comment]
We'll continue this issue here: https://github.com/spatie/ray/issues/44
