### ISSUE TITLE
Ray doesn't work in Lumen

### ISSUE THREAD

**Issue by mennovanhout** [spatie/laravel-ray#71]
**Describe the bug**
Ray doesn't work in Lumen the calls do not appear in the desktop app.

**Versions**
1.2.2.0
- spatie/ray package version: 1.5.5
- spatie/laravel-ray package version (if applicable):  1.3.4

PHP version: 8.0
Lumen version: 8

**To Reproduce**
1. Create a new lumen project
2. Register Ray service provide in app.php:
`$app->register(\Spatie\LaravelRay\RayServiceProvider::class);`
3. Add a ray log in web.php
```
$router->get('/', function () use ($router) {
    ray('My first ray call');

    return $router->app->version();
});
```

**Expected behavior**
A message in the ray desktop app.

 - OS: Windows with Docker
I've also published ray.php in the root of the project (using rays publish command).
And changed the host to: host.docker.internal

**Comment by freekmurze** [comment]
I don't think this is related to Lumen. Could you test this in Laravel app in the same environment?

**Comment by chris-doehring** [comment]
I also think that this is related to your environment. Works fine with my Lumen 8 installation under php 8 and latest Ray.

**Comment by freekmurze** [comment]
I'm going to close this one, as it seems to be working in Ray. If you are still have problems, please open up a new, specific issue.

**Comment by mennovanhout** [comment]
Hi there, seems to be a problem with my work laptop. Anyidea why?

**Comment by chris-doehring** [comment]
Hi @mennovanhout, without any information what settings you have configured in your `ray.php` config or Ray client, unfortunately no one can give you any advice.

**Comment by chris-doehring** [comment]
You wrote that you have published your `ray.php` in the root directory. That could be the problem. Try to put it into your `/config` directory. It's not needed to configure it in your `app.php` afterwards, apart from the `RayServiceProvider`.

**Comment by mennovanhout** [comment]
> You wrote that you have published your `ray.php` in the root directory. That could be the problem. Try to put it into your `/config` directory. It's not needed to configure it in your `app.php` afterwards, apart from the `RayServiceProvider`.

Reading the documentation it needs to be in the root. Also there is no issue regarding the repository on my home pc it works well.
Something is blocking it on my work laptop. Probably something to do with Windows domain control. I do have an administrator account to the laptop. But the allow are laptops to use ray we need to know what kind permissions or windows settings are needed.

**Comment by oliverhermanni** [comment]
@mennovanhout Did you change your host in `ray.php` as shown in the [docs](https://spatie.be/docs/ray/v1/configuration/docker)?

**Comment by mennovanhout** [comment]
> @mennovanhout Did you change your host in `ray.php` as shown in the [docs](https://spatie.be/docs/ray/v1/configuration/docker)? 

Yes. Also the repository works on another windows machine. Just not the work laptop.

**Comment by makakken** [comment]
argh... just bought ray license today to debug a lumen projekt, but i get a strange error now:
`Target [Illuminate\Contracts\Routing\ResponseFactory] is not instantiable.` Is someone able to tell me how to resolve that?
