### ISSUE TITLE
Clicking on the filename under a debug message isn't sending me to the file in Sublime

### ISSUE THREAD

**Issue by simderoemer** [spatie/laravel-ray#72]
Thanks for the great app guys. Just reporting this bug, hope it's helpful feedback.

**Describe the bug**
In my ray preferences, I have specified that my IDE is Sublime.
When I am clicking the filename under a debug message within my trial version of Ray, I am expecting to be taken back to Sublime and be taken to the line of code where I added the debug message.

**Versions**
Ray version (you can see this in "About Ray"): 1.2.2 (Trial)

**To Reproduce**
1. Open ray
2. Set my IDE in ray to 'Sublime'
3. Open sublime text
4. Add a ray() debug message to my code
5. See the error within Ray
6. Click on the filename

**Expected behavior**
I'm expecting to sent back to sublime, at the right file and line number.

**Screenshots**
![Screenshot 2021-01-12 at 15 02 45](https://user-images.githubusercontent.com/355039/104331680-406d1000-54e7-11eb-9cf7-16ff0041e4d6.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] macOS
 - Version [e.g. 22] 10.15.7
 
 **Additional context**
Sublime Text Version 3.2.2 Build 3211

**Comment by freekmurze** [comment]
@AdrianMrn do users need to register that Sublime URL protocol?

**Comment by AdrianMrn** [comment]
I believe so. @simderoemer Sublime doesn't allow opening the editor by default, could you try installing this and report back? https://github.com/saetia/sublime-url-protocol-mac

If that works, we'll find a place to add it to the docs.

**Comment by simderoemer** [comment]
That's fixed it, thank you.
Thanks for your help and making these great tools,

S
