### ISSUE TITLE
After your latest log of your trail, you can't re-watch your 10 results

### ISSUE THREAD

**Issue by NoahNxT** [spatie/laravel-ray#76]
**Describe the bug**
As mentioned in the application you'll get 10 free logs. The issue is that you can't re-watch your logs that you made because of the popup model that asks to activate your license.

**Versions**
Ray version 1.2.3.0:

Composer: spatie/laravel-ray                 1.3.5              Easily debug Laravel apps

PHP version: PHP 8.0.1 (cli)
Laravel version:  v8.21.0

1. start a trail
2. Execute 9 ray logs
3. The 10th log is a JSON

**Expected behavior**
A smaller popup alert in the top corners that warns you that you need to activate your license or otherwise you can't use ray in the further progress of your project.

**Screenshots**
![2021-01-12 20_26_35-Window](https://user-images.githubusercontent.com/58152024/104363745-f0f20880-5515-11eb-8971-83ae462d2bdc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64-bit
 - Version: Build 19041

**Comment by freekmurze** [comment]
This is expected behaviour. To get rid of this, you should get a license.
