### ISSUE TITLE
Queries with long single-values are cut off

### ISSUE THREAD

**Issue by squatto** [spatie/laravel-ray#77]
**Describe the bug**
I have a query that inserts into a logging table that has 3 `json` columns. When using `showQueries()`, the query is cut off and I'm unable to horizontally scroll to see it all.

**Versions**
Ray version (you can see this in "About Ray"): 1.2.3

You can use `composer show` to get the version numbers of:
- spatie/ray package version: 1.5.0
- spatie/laravel-ray package version (if applicable):  1.3.4

PHP version: 7.4.14
Laravel version: 8.21.0

**To Reproduce**
1. Enable `showQueries()`
2. Insert into a model that has a `json` field, and use a large `array` for the value

**Expected behavior**
I'd like to be able to see the entire query, either by scrolling left or - more preferably - by wrapping the value.

**Screenshots**
![image](https://user-images.githubusercontent.com/748444/104383119-8d9fb080-54ec-11eb-85e8-d9d3fb87d820.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: Big Sur 11.1 (20C69)
 
**Additional context**
N/A

**Comment by AdrianMrn** [comment]
@willemvb I can't seem to find the correct combination of classes to get the lines to properly wrap.

You can use this in Query.tsx to test it (you will still have to run `a test-query` in the demo app):
```
const formattedQuery = sqlFormatter.format(
        'SELECT user_iduser_iduser_iduser_iduser_iduser_iduser_iduser_iduser_iduser_iduser_iduser_iduser_iduser_iduser_iduser_iduser_iduser_iduser_iduser_id FROM users;'
    );
```

**Comment by AdrianMrn** [comment]
This will be fixed in the next release of Ray, coming today or tomorrow!
