### ISSUE TITLE
Lumen Support

### ISSUE THREAD

**Issue by chris-doehring** [spatie/laravel-ray#8]
Hey guys,

congrats on the release of ray! It would be nice if the Laravel integration could also support Lumen. I have tried it locally and the only blockers should be the following:
* `Spatie\LaravelRay\DumpRecorder\DumpRecorder` requires the Application Contract which Lumen does not support, but it could be replaced by `Illuminate\Container\Container` instead
* The `RayServiceProvider` registers a blade listener which is not supported by Lumen. A check if it is loaded could resolve this

If I have enough time later on I will create a pull request to resolve this, but it would be nice to hear your opinion regarding Lumen support within this package.

**Comment by freekmurze** [comment]
If there are not too much code changes, I would consider merging in your PR. Thanks for your time you spend on this.

**Comment by freekmurze** [comment]
Closing this for now, if you have questions around this, feel free to continue the conversation here.
