### ISSUE TITLE
ray:publishconfig does not update file correctly with --homestead/--docker option

### ISSUE THREAD

**Issue by craftyshaun** [spatie/laravel-ray#81]
HI Team;

I just preformed a fresh install of `spatie/laravel-ray` in my laravel 7 install and published the config as per the docs with the `--homestead` option. The file was not replaced with the defaults.

I checked the code to see how it does it and found the issue on the below line 
https://github.com/spatie/laravel-ray/blob/995a445e323a269af30285b683ebb3eb4b1e50c9/src/Commands/PublishConfigCommand.php#L35

The commit to use environment variables meant the publish command was broken.
https://github.com/spatie/laravel-ray/blob/995a445e323a269af30285b683ebb3eb4b1e50c9/stub/ray.php#L28

I'm happy to try and raise a PR to update the defaults of the `env` call to the homestead IP or the docker address for each of the occurrences if @freekmurze thinks this is the right way to handle this (sorry open-source contrib n00b).

**Comment by squatto** [comment]
@craftyshaun Great catch! The recent change to use environment variables was made by me. I should have caught this breakage - my bad there! I just submitted PR #82 to fix this.
