### ISSUE TITLE
Not working for me in WordPress

### ISSUE THREAD

**Issue by w3guy** [spatie/laravel-ray#92]
When I bought ray, I installed the composer package and it was working.

Today, I installed the WordPress plugin, removed the composer package and updated Ray to the latest version.

Now it doesn't work.

Note: I use PHPStorm.

I have restarted my computer and Mamp pro couple of times and still not working.

**Comment by freekmurze** [comment]
Maybe your WordPress installation thinks it's in production?

Try calling ray()->enable()

**Comment by w3guy** [comment]
@freekmurze add this to your WordPress doc

Local environment has to be explicitly defined in wp-config.php file like so

`define( 'WP_ENVIRONMENT_TYPE', 'local' );`

I did that and it started working.
