### ISSUE TITLE
Balde custom directives fails

### ISSUE THREAD

**Issue by alikmanukian** [spatie/laravel-ray#94]
Hey guys!

thanks for great tools. 
But unfortunately after install laravel-ray, some of my blade custom directives are broken. 
For example `@interia` is not working.
After commenting `Blade::directive('ray')` everything fixes. 

Please fix this bug.

**Comment by freekmurze** [comment]
Hi, in our projects this is working perfectly.

If you are still having troubles, please create a minimal example app to easily reproduce this problem and open a new issue using the issue template.

**Comment by alikmanukian** [comment]
Hi, I've found the reason why it brokes other directive after `view:clear`. 
You put registerBladeDirectives() in RayServiceProvider::register function instead of boot function. 
Everything works find after move call registerBladeDirectives into boot function.

**Comment by nocodelab** [comment]
Hello guys, I'm having the same problem with ray when using packages with custom blade directives.
See this one with the package akaunting/laravel-money:

<img width="664" alt="Screenshot 2021-05-12 at 17 59 21" src="https://user-images.githubusercontent.com/4540118/118006708-c8efa600-b34b-11eb-9459-79022280e757.png">

**Comment by nocodelab** [comment]
I confirm that the workaround proposed by @alikmanukian works smoothly.
@freekmurze I believe you should update the RayServiceProvider accordingly.

<img width="459" alt="Screenshot 2021-05-12 at 18 06 46" src="https://user-images.githubusercontent.com/4540118/118007845-d194ac00-b34c-11eb-9d79-4d00b9279c0f.png">
